monitor.alsa.rules = [
  {
    matches = [
      {
        device.name = "~alsa_card.pci-0000_01_00.*"
      }
    ]
    actions = {
      update-props = {
        session.dont-restore-off-profile = true
      }
    }
  }
]
