[General]
ColorScheme=Breeze Dark
LastPlayedFile=file:///mnt/newstorage/torrents/show/You.S05.1080p.NF.WEB-DL.H.264-EniaHD/You.S05E02.Blood.Will.Have.Blood.1080p.NF.WEB-DL.H.264-EniaHD.mkv

[Subtitles]
FontFamily=Verdana
FontSize=43
