[xboxdrv]
silent = true
dpad-as-button = true
detach-kernel-driver = true

[ui-clear]

[ui-buttonmap]
a = BTN_LEFT
b = XK_Escape
x = XK_space
y = KEY_LEFTMETA+KEY_F9

guide+b = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_q
guide+rb = KEY_LEFTMETA+XK_Right
guide+lb = KEY_LEFTMETA+XK_Left
guide+tl = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_space
guide+a = XK_Return
guide+start = KEY_LEFTMETA+XK_a
guide+y = KEY_LEFTMETA+XK_e
guide+du = KEY_VOLUMEUP
guide+dd = KEY_VOLUMEDOWN
guide+dl = KEY_LEFTMETA+XK_slash
guide+dr = KEY_PLAYPAUSE
guide+lt = KEY_LEFTMETA+XK_m
guide+rt = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_Right
guide+back = KEY_LEFTALT+KEY_DELETE
guide+tr = KEY_LEFTMETA+XK_f
guide+x = KEY_LEFTCTRL+XK_f

start+x = KEY_LEFTMETA+XK_d
start+y = KEY_LEFTMETA+XK_q
start+lb = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_s
start+rb = KEY_LEFTMETA+KEY_LEFTCTRL+XK_v
start+back = KEY_LEFTMETA+XK_grave

tl+tr = KEY_LEFTMETA+KEY_F11
lb = XK_Left
rb = XK_Right
lt = BTN_SIDE
rt = BTN_EXTRA
dl = KEY_LEFT
dr = KEY_RIGHT
du = KEY_UP
dd = KEY_DOWN

[ui-axismap]
x1^dead:4000 = REL_X:5:8
y1^dead:4000 = REL_Y:5:8
y2^dead:8000 = REL_WHEEL:-1:1
