[xboxdrv]
silent = true
dpad-as-button = true
detach-kernel-driver = true

[ui-clear]

[ui-buttonmap]
guide = XK_Escape
a = BTN_LEFT
b = BTN_RIGHT
x = KEY_LEFTMETA+XK_slash
y = KEY_LEFTMETA+KEY_F9

guide+b = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_q
guide+rb = KEY_LEFTMETA+XK_Right
guide+lb = KEY_LEFTMETA+XK_Left
guide+tl = KEY_LEFTMETA+XK_f
guide+a = KEY_LEFTMETA+XK_e
guide+start = KEY_LEFTMETA+XK_a
guide+y = KEY_LEFTMETA+XK_grave
guide+du = KEY_VOLUMEUP
guide+dd = KEY_VOLUMEDOWN
guide+dl = KEY_F14
guide+dr = KEY_PLAYPAUSE
guide+lt = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_Left
guide+rt = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_Right
guide+x = KEY_LEFTALT+KEY_DELETE
guide+back = KEY_LEFTMETA+XK_BackSpace
start+lb = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_s
start+rb = KEY_LEFTMETA+KEY_LEFTCTRL+XK_v

tl+tr = KEY_F11
start = KEY_LEFTMETA+XK_d
back = KEY_LEFTMETA+XK_q
lb = XK_Left
rb = XK_Right
lt = BTN_MIDDLE
rt = KEY_LEFTMETA+KEY_LEFTSHIFT+XK_space
dl = KEY_LEFT
dr = KEY_RIGHT
du = KEY_UP
dd = KEY_DOWN

[ui-axismap]
x1^dead:8000 = REL_X:5:8
y1^dead:8000 = REL_Y:5:8
y2^dead:8000 = REL_WHEEL:3:1
