preload = /home/lahcen/Pictures/Wallpapers/ice.png
wallpaper = HDMI-A-1, /home/lahcen/Pictures/Wallpapers/ice.png
wallpaper {
	monitor =
	path = /home/lahcen/Pictures/Wallpapers/ice.png
	fit_mode = cover
	
}
